[build]
  command = "npm run build"
  publish = "build"

# Tắt toàn bộ post-processing (gộp/minify lại JS/CSS/HTML…) để không đổi đường dẫn bundle
[build.processing]
  skip_processing = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
